ACTIVITY_MAP = {
    "email etc.":"Email & IM",
    "emails etc.":"Email & IM",
    "emails misc": "Email & IM",
    "age files action email": "Email & IM",
    "pmpa call":"PMPA",
    "1":"Meeting",
    "capa": "CAPA",
    "em/etc": "Em Etc",
    "unplanned audit support":"Audit",
    "meetings/mentoring": "Training/Mentoring",
    "procesing question":"Question",
    "all employee meeting": "Meeting",
    "unplanned questions, discussion with med safety":"Question",
    "review of lit pe for pmpa":"PMPA",
    "training cx email misc": "Training/Mentoring",
    "voyage integrate into next gch meeting": "Meeting",
    "correction of hypercare event":"Hypercare",
    "trainng": "Training/Mentoring",
    "fywt assigning/gfe ageing meeeting": "Meeting",
    "new schedule template review & ri meeting":"RI",
    "weekly ttvr meeting": "Meeting",
    "ri meeting & 1":"RI",
    "lab call/capa meeting":"CAPA",
    "weekly scheudle": "Metrics & Schedule",
    "meterics, scrum, schedule": "Metrics & Schedule",
    "fyw tool": "Metrics & Schedule",
    "weekly schedule": "Metrics & Schedule",
    "career fair launch event cic building":"Career Development",
    "scrum & ri meeting for update":"Scrum & Action",
    "pmpa date request":"PMPA",
    "(investigaion training spider)":"Training/Mentoring",
    "quality-day prep meeting": "Meeting",
    "shipping to plexus (liberant)":"shipment",
    "pmpa & lab meeting":"PMPA",
    "adn career fair planning meeting":"Career Development",
    "wip pull etc": "Metrics & Schedule",
    "monthly precedent event meeting":"Meeting",
    "metrics/scrum/schedule for tomorrow": "Metrics & Schedule",
    "metrics, tuesday schedule": "Metrics & Schedule",
    "scrum & audit meeting":"Scrum & Action",
    "scrum/check in":"Scrum & Action",
    "reviewed and processed emails from when i was out of office (does not include emails from engineers)": "Email & IM",
    "pulled work": "Metrics & Schedule",
    "pulled work tool, yellow belt training": "Metrics & Schedule",
    "weekly schedule & heijunka meeting": "Metrics & Schedule",
    "weekly scheudle & audit resources update": "Metrics & Schedule",
    "team leads meeting & cornerstone": "Meeting",
    "1:1 with elaine": "Meeting",
    "shoebox appeal 12pm - 2pm": "Meeting",
    "pmpa meeting & lab meeting":"PMPA",
    "ri meeting & monthly problem solving":"RI",
    "training/mentoring": "Training/Mentoring",
    "training, graduate clinic": "Training/Mentoring",
    "cornerstone, checking agile files, changing password issue":"Cornerstone",
    "training, meeting": "Training/Mentoring",
    "admin, vaccine appointment, reviewing document":"Admin",
    "cornerstone, meeeting":"Cornerstone",
    "training, lab analysi": "Training/Mentoring",
    "cornerstone+closurefast training review meeitng": "Training/Mentoring",
    "line tour, training": "Training/Mentoring",
    "working on a3 dmaic":"Problem Solving",
    "emails, set up in the lab and cornerstone":"Email & IM",
    "email to cell to notify about a issue":"Email & IM",
    "admin (emails etc...)":"Admin",
    "scrum & problem solving":"Problem Solving",
    "meeting+deco tidy up": "Meeting",
    "fola training product analysis write up review": "Training/Mentoring",
    "meetings - voyager transfer and helifx test doc update": "Meeting",
    "training corrections and re-work": "Training/Mentoring",
    "emails, raisng ticket for my cornerstone issue":"Email & IM",
    "shipping devices to nellcor, email":"Email & IM",
    "meetings - crdn tier 2 & sh r&d": "Meeting",
    
    "admin, training":"Admin",
    "(discussion with aurelie - closurefast device for nellcor)": "Collaboration",
    "1 to 1 meeting": "Meeting",
    "tier meeting": "Meeting",
    "meeting with aurelie (ifu-closurefast)": "Meeting",
    "e-mails about manufacturing assessment":"Email & IM",
    "shipping":"shipment",
    "emails, etc":"Email & IM",
    "reading through crdn product document": "Documentation",
    "reading over documents for spider analysis training": "Documentation",
    "reading through coronary product guide": "Documentation",
    "self training": "Training/Mentoring",
    "reading coronary accessories ppt": "Training/Mentoring",
    "arranging shipment of products to plymouth":"shipment",
    "sh live case video":"Reviewing Documents & Case Video",
    "looking up on how to analyse video":"Reviewing Documents & Case Video",
    "cleaning new desk and set up, admin":"Admin",
    "gemba slide prep and gemba":"Gemba",
    "emails & admin":"Email & IM",
    "reading crdn document": "Documentation",
    "looking over past file":"WIP Review",
    "1:1 and verso meeting": "Meeting",
    "setting up in new desk":"Admin",
    "looking over dmaic training note":"Problem Solving",
    "admin & desk sorting (after movemnt by facilities)":"Admin",
    "meeting with cell/investigations about analysi": "Meeting",
    "sha tier": "Meeting",
    "sorting shipment":"shipment",
    "crdn tier 2": "Meeting",
    "setting up devices to send":"Admin",
    "relabelling archived device":"Admin",
    "desk set up":"Admin",
    "meeting in lab": "Meeting",
    "meeting with cell/investigation": "Meeting",
    "writing up spider analysis cheat sheet for training": "Documentation",
    "sorting out power supply to new desk":"Admin",
    "sh/a meeting": "Meeting",
    "shipping device to us - aortic capa":"CAPA",
    "sorting out req's with cell":"Collaboration",
    "nicola lab audit walk through":"Audit",
    "new desk setup":"Admin",
    "reading aortic educational document": "Documentation",
    "emails + cell querie":"Email & IM",
    "emails, fwt, working on reopened file":"Email & IM",
    "reading aortic documanet": "Documentation",
    "emails, admin":"Email & IM",
    "lab cleaning":"Admin",
    "laptop forced restart (new update)": "IT Issue/Update",
    "meeting (voyager fume hood)": "Meeting",
    "nellcor shipping":"shipment",
    "q3 town hall recording": "Meeting",
    "emails, dealing with issues from devices,dmaic":"Email & IM",
    "cornerstone, voyager meeting":"Cornerstone",
    "fwt, reading agile document": "Metrics & Schedule",
    "liberant training meeting": "Training/Mentoring",
    "fwt, emails, training": "Metrics & Schedule",
    "emails,cornerstone,dmaic":"Email & IM",
    "admin, emails, shipping and cornerstone training":"Admin",
    "townhall recording": "Meeting",
    "reading steerant and aortic device document": "Documentation",
    "shipments and tracking":"shipment",
    "fwt etc": "Metrics & Schedule",
    "tom shiel parkmore townhall": "Meeting",
    "liberant training": "Training/Mentoring",
    "meeting, prep": "Meeting",
    "emails + tracking querie":"Email & IM",
    "admin, cornerstone":"Admin",
    "catching up on emails, fwt etc":"Email & IM",
    "cell queries + deco tidy up":"Question",
    "morning admin, chemical change":"Admin",
    "network issues. change order": "IT Issue/Update",
    "shipping, emails, cornerstone": "shipment",
    "training/mentoring": "Training/Mentoring",
    "server issue": "IT Issue/Update",
    "live case videos, cornerstone":"Reviewing Documents & Case Video",
    "emails, admin, project":"Email & IM",
    "graduates clinic, cornerstone":"Cornerstone",
    "fwt, it issues, training": "IT Issue/Update",
    "rch review, updating a fourmies wi, emails, fw, career development plan":"Career Development",
    "shipments, devices returned in error": "shipment",
    "change order docs updated to new template":"Change Order",
    "lab meeting sorting cf": "Meeting",
    "meetings, calls, shipping device": "Meeting",
    "reading training document": "Training/Mentoring",
    "meetings, server issue": "Meeting",
    "fwt, lab meeting": "Meeting",
    "meeting regarding activa sc device to be shipped, dealing with the activa sc": "Meeting",
    "emails, dealing with req's and devices to be shipped":"Email & IM",
    "emails, redoinging lost work":"Email & IM",
    "emails, cornerstone etc":"Email & IM",
    "bagging the devices, meeting": "Meeting",
    "admin and shipping":"Admin",
    "server issues and then rework on file from cell": "IT Issue/Update",
    "rpa lab meeting, network isssues, emails etc.": "RPA Meeting/Action",
    "network down": "IT Issue/Update",
    "meetings and admin": "Meeting",
    "no net work, agile": "IT Issue/Update",
    "mornign admin, lab meeting, checking sh hold devices for update": "Meeting",
    "emails, lab meeting":"Email & IM",
    "dealing with issues from cell, sh&a meeting": "IT Issue/Update",
    "dmaic, email":"Problem Solving",
    "finding work tool, email":"Email & IM",
    "emails, morning admin etc, lab meeting":"Email & IM",
    "emails, fwt, lab set up":"Email & IM",
    "chemical change, cleaning after deco":"Admin",
    "emails, workday update":"Email & IM",
    "emails, dealing with devices to be shipped":"Email & IM",
    "admin, ordering chemicals.":"Admin",
    "emails, finding work tool,":"Email & IM",
    "1:1 with aurelie - career development discussion":"Career Development",
    "career devopment plan update":"Career Development",
    "cleaning":"Admin",
    "cleaning and email":"Admin",
    "meeting tier": "Meeting",
    "label printer issue": "IT Issue/Update",
    "meeting and email": "Meeting",
    "shipping closure fast device":"shipment",
    "sha meeting, mfg device review": "Meeting",
    "re-taking photos for cell & reviewing code":"Coding",
    "meeting, helping team member": "Meeting",
    "dealing with cell issues and email":"Email & IM",
    "1 to 1 development meeting":"Career Development",
    "email, fw, discussing file ect":"Email & IM",
    "chemical order check and email":"Email & IM",
    "crdn meeting": "Meeting",
    "catching up on email":"Email & IM",
    "rnd reviewing device, call with santa ana": "Meeting",
    "emails, fwt ect":"Email & IM",
    "qch - updating fourmies doc": "Documentation",
    "meeting crdn": "Meeting",
    "emails for tergazyme order":"Email & IM",
    "reviewing dmaic training note":"Problem Solving",
    "morning admin, r&d/pmq dcb review":"Admin",
    "admin, cidex order issue":"Admin",
    "shipping devices for nellcor":"shipment",
    "learning how to analyse video":"Reviewing Documents & Case Video",
    "launcher file with ciara and meeting": "Meeting",
    "on a call with it": "Meeting",
    "trying to download fwt": "Metrics & Schedule",
    "conerner stone":"Cornerstone",
    "admin (emails,fwt etc)":"Admin",
    "concerto email":"Email & IM",
    "fwt emails ((15)": "Metrics & Schedule",
    "fw, emails, ect": "Metrics & Schedule",
    "emails, training, fw":"Email & IM",
    "emails for training, reporting cell":"Email & IM",
    "fwt, email": "Metrics & Schedule",
    "weekly complaints call": "Meeting",
    "sorting dated cell querie":"Question",
    "meeting tl": "Meeting",
    "looking at launcher for grainne and helping siva":"Collaboration",
    "gemba walk":"Gemba",
    "fw/heat map": "Metrics & Schedule",
    "fwt issue": "Metrics & Schedule",
    "sha weekly meeting": "Meeting",
    "fw/email ect": "Metrics & Schedule",
    "reading about coronary accessorie": "Documentation",
    "sorting new desk":"Admin",
    "change order sorting":"Change Order",
    "emails and cornerstone":"Email & IM",
    "emails/purchasing":"Email & IM",
    "tier 2 crdn meeting": "Meeting",
    "liberant launch meeting": "Meeting",
    "reviewing helifx document update redline":"Redline",
    "admin and training correction":"Admin",
    "morning set up, emails fwt etc.":"Email & IM",
    "rch equipment check with aurelie":"Collaboration",
    "reviewing file for trainee": "Training/Mentoring",
    "safety notices & merge meeting": "Meeting",
    "ri, pmpa & lab meeting":"RI",
    "live case video":"Reviewing Documents & Case Video",
    "reviewing documents, live case video":"Reviewing Documents & Case Video",
    "reviewing documents, projects list":"Reviewing Documents & Case Video",
    "line tour":"Tour",
    "deco tidy up+cell emailing":"Email & IM",
    "pharma lab tour":"Tour",
    "b2 line tour":"Tour",
    "capa 726178 meeting":"CAPA",
    "proforma training":"Proforma",
    "ri meeting & safety communication":"RI",
    "q":"Question",
    "1 to 1":"Meeting",
    "metrics & monday's schedule": "Metrics & Schedule",
    "training (rr, task, comms)": "Training/Mentoring",
    "questions, cornerstone":"Cornerstone",
    "workflow meeting":"Meeting",
    "admin/pack up desk":"Admin",
    "imdrf":"Coding",
    "capa meeting": "CAPA",
    "id&e meeting":"Meeting",
    "revise rfr codes for trending & analytic":"Coding",
    "mentoring/hypercare": "Training/Mentoring",
    "delivery) practicel letter": "Training/Mentoring",
    "meeting/training": "Training/Mentoring",
    "hvt pmcf gch uat review mir form meeting/": "Meeting",
    "capa 726178 support prep & meeting":"CAPA",
    "4 am meetings ~ total 2 hrs": "Meeting",
    "backroom internal audit training / ri / team collab":"Audit",
    "mir form meeting": "Meeting",
    "bank holiday":"OOO",
    "bank hol":"OOO",
    "scrum meeting":"Scrum & Action",
    "mir meeting, sending mir/lit rr": "Meeting",
    "review event with svt/tct members, attached faxes to pes":"Collaboration",
    "vacation": "OOO",
    "qa report out":"QA",
    "misc/admin":"Admin",
    "audit question":"Audit",
    "a3 work": "Problem Solving",
    "letter requested by pmpa / sent for pmpa review":"PMPA",
    "conerstone training/email response":"Cornerstone",
    "talking with inv team regarding event/customer letter":"Collaboration",
    "replying emails, reaching out to prs":"Email & IM",
    "benefits/cas ri + ri meeting":"RI",
    "audit nc admin (assign training, collaborate with rpa, request data)":"Audit",
    "team leads meeting/capa 726178 inv meeting/audit updates meeting":"CAPA",
    "audit nc prep":"Audit",
    "cas + svt ri":"RI",
    "lates meeting/1:1/ri":"RI",
    "training with sean for gfe/fax reply, working on lit event": "Training/Mentoring",
    "priority customer letter/cornerstone training":"Cornerstone",
    "ri/late":"RI",
    "any final a3 touches needed": "Problem Solving",
    "a3":"Problem Solving",
    "mc3 call":"Meeting",
    "lab call":"Meeting",
    "coaching": "Training/Mentoring",
    "audit nc":"Audit",
    "cas ri/lates triage and inv":"RI",
    "internal audit meeting":"Audit",
    "scrum/checkin": "Scrum & Action",
    "gemba prep + gemba meeting/capa 726178 meeting":"Meeting",
    "cas ri triage & training/ cornerstone":"RI",
    "reg inquiries/ am meetings (ri/oct/lates)":"RI",
    "capa call": "CAPA",
    "mentoring/shadowing and meeting": "Training/Mentoring",
    "computer failure requiring replacement": "IT Issue/Update",
    "in-person discussion":"Collaboration",
    "internet issue": "IT Issue/Update",
    "requesting proforma/creating evnts for ppm event":"Proforma",
    "sending emails to pmpa for ous request of data/corrections with ms":"PMPA",
    "wip report": "Metrics & Schedule",
    "capa working session": "CAPA",
    "capa update call": "CAPA",
    "pmpa weekly meeting": "PMPA",
    "misc/in-office interruption":"Collaboration",
    "ms teams chats/interruption":"Email & IM",
    "finish scheduling": "Metrics & Schedule",
    "scheduling": "Metrics & Schedule",
    "wip mgmt": "Metrics & Schedule",
    "wip management": "Metrics & Schedule",
    "wip management and work report assignment": "Metrics & Schedule",
    "late mdr/enterprise qa":"QA",
    "rs nav inbox support":"RS Inbox",
    "mazor inbox":"RS Inbox",
    "software request": "IT Issue/Update",
    "cst tier 2" : "Meeting",
    "aging review":"Aged WIP Review",
    "tier 1 / round table" : "Meeting",
    "tech sme (cw, is, iris, etc)":"Project Work",
    "qa support / corrections (enterprise)":"QA",
    "late mdrs/escalations/rr tts":"RRTT",
    "1:1s (including ad-hoc)" : "Meeting",
    "code update":"Coding",
    "qa corrections (enterprise)":"QA",
    "huddle" : "Meeting",
    "town halls, aem" : "Meeting",
    "town halls,aem": "Meeting",
    "town halls/aem" : "Meeting",
    "tl heijunka": "Metrics & Schedule",
    "schedule": "Metrics & Schedule",
    "metric": "Metrics & Schedule",
    "ri support":"RI",
    "tier-tue" : "Meeting",
    "tier-thur" : "Meeting",
    "admin (emails, etc)":"Admin",
    "mainenance of cq tools (coding, odc, inv)":"Project Work",
    "late review + rrtt":"RRTT",
    "wip schedule, setting up metrics table": "Metrics & Schedule",
    "audit checkin" : "Audit",
    "heijunka review/update" : "Metrics & Schedule",
    "scrumb": "Scrum & Action",
    "brian meeting, scrum, collaboration": "Meeting",
    "training/letter shadowing, locating trainee work, email": "Training/Mentoring",
    "trainee (onboarding, cross-training)": "Training/Mentoring",
    "mentorship": "Training/Mentoring",
    "late reg report / enterprise qa":"QA",
    "capa support":"CAPA",
    "shadowing": "Training/Mentoring",
    "response to emails for product analysis, studies and literature processing question": "Email & IM",
    "reviewing letters, meeting" : "Meeting",
    "responding to emails and team collaboration": "Email & IM",
    "mtg" : "Meeting",
    "ng, coding, email/admin":"Next Gen",
    "ng, risk management, meetings, lates/event review, collab, gb, email/admin": "Meeting",
    "lates/event review, collab, ng, gb, email/admin": "Email & IM",
    "meetings, collaboration, coding, gb, emails, collab, event review":"Meeting",
    "scheduling/heijunka update": "Metrics & Schedule",
    "ng, collaboration, coding, meetings, event reviews, emails/admin":"Next Gen",
    "ng, collaboration, coding, meetings, lates/event reviews, emails/admin": "Meeting",
    "ng, gb, coding, meetings, event reviews, emails/admin": "Email & IM",
    "ng, gb, collaboration, meetings, event reviews, emails/admin": "Collaboration",
    "collab":"Collaboration",
    "team collab":"Collaboration",
    "20 minutes mir call":"Meeting",
    "ng, collaboration, event reviews, emails/admin":"Green Belt",
    "gb, collaboration, coding, meetings, event reviews, emails/admin": "Event Reviews",
    "late" : "Late Review",
    "brian meeting": "Meeting",
    "comm, task , rr practice": "Training/Mentoring",
    "training review/questions": "Training/Mentoring",
    "e-mail": "Email & IM",
    "scrum/checking": "Scrum & Action",
    "heijunka population": "Metrics & Schedule",
    "french reimbursement query":"Question",
    "clinical query":"Question",
    "fywt/heijunka population": "Metrics & Schedule",
    "heijunka": "Metrics & Schedule",
    "aging wip review":"Aged WIP Review",
    "aged events review":"Aged WIP Review",
    "aging files review":"Aged WIP Review",
    "sha qa review": "QA",
    "clinical task training" : "Clinical Task",
    "training meeting": "Training/Mentoring",
    "problem solving meeting":"Problem Solving",
    "training (shadowing, scheduling, meeting, etc.)": "Training/Mentoring",
    "scrim": "Scrum & Action",
    "review feedback": "Feedback",
    "contego hypercare meeting": "Meeting",
    "rpa lab meeting": "RPA Meeting/Action",
    "team scrum 7 x": "Scrum & Action",
    "team scrum 6 x": "Scrum & Action",
    "complaint coding call": "Meeting",
    "one - one with manager": "Meeting",
    "mvp ftq question": "Question",
    "1-1 with manager": "Meeting",
    "fywt/heijunka": "Metrics & Schedule",
    "parklief":"Parklife",
    "rpa meeing": "RPA Meeting/Action",
    "tm help":"Collaboration",
    "rpa minutes and action": "RPA Meeting/Action",
    "med safety meeting": "Meeting",
    "actions from meeting": "Meeting",
    "pto":"OOO",
    "tl activities meeting": "Meeting",
    "clinical safety plan email":"Email & IM",
    "im chat on technical issue":"Email & IM",
    "teams calls/im":"Email & IM",
    "aortil call": "Meeting",
    "clinical meeting": "Meeting",
    "clinical investigation meeting": "Meeting",
    "team support":"Collaboration",
    "1to": "Meeting",
    "audit report":"Audit",
    "open file review": "WIP Review",
    "corrections/review file": "WIP Review",
    "tl support":"Collaboration",
    "tm support":"Collaboration",
    "' tm support":"Collaboration",
    "review file": "WIP Review",
    "aging review": "Aged WIP Review",
    "follow up on device or information on aged file": "Aged WIP Review",
    "querie":"Question",
    "started compiling details to prepare email for clinical team" :"Email & IM",
    "cornerstone, email":"Cornerstone",
    "film review meeting": "Meeting",
    "other querie": "Question",
    "meet": "Meeting",
    "weekly meeting": "Meeting",
    "email catch up": "Email & IM",
    "im": "Email & IM",
    "internal audit": "Audit",
    "ri response":"RI",
    "pmq cr pre-meeting q's review": "PMQ pre-meeting review Q's",
    "other queurie": "Question",
    "cqxm querie": "Question",
    "jumped to another meeting) global quality meeting": "Meeting",
    "it support/restart": "IT Issue/Update",
    "capa remediation review": "CAPA",
    "ect letter training": "Training/Mentoring",
    "cqxm training":"Training/Mentoring",
    "ri": "RI",
    "ri aortic meeting": "RI",
    "scrum&action": "Scrum & Action",
    "scrum & action": "Scrum & Action",
    "scrum and action": "Scrum & Action",
    "scrum& action": "Scrum & Action",
    "aged file review": "Aged WIP Review",
    "scrum &action": "Scrum & Action",
    "call": "Meeting",
    "investigation meeting": "Meeting",
    "meeting": "Meeting",
    "meeeting": "Meeting",
    ". meeting": "Meeting",  # extra safety; usually cleaned earlier
    "qa review": "QA",
    "qa review/correction": "QA",
    "qa review/update": "QA",
    "risk management knowledge sharing call": "Risk Management Knowledge Sharing Call",
    "risk mangement knowledge sharing call": "Risk Management Knowledge Sharing Call",
    "risk mgmt kniwledge session": "Risk Management Knowledge Sharing Call",
    "film meeting": "Meeting",
    "coding/risk mgmt meeting": "Meeting",
    "coding meeting": "Meeting",
    "trainning": "Training/Mentoring",
    "film meeting": "Meeting",
    "med safety call": "Meeting",
    "cqxm all team meeting": "Meeting",
    "corner stone": "Cornerstone",
    "next gen support": "Next Gen",
    "literature meeting": "Meeting",
    "laptop turning on": "Set Up",
    "emails and shipment": "Email & IM",
    "emails, fwt, metric": "Email & IM",
    "emails, tw," : "Email & IM",
    "liberant meeting": "Meeting",
    "tier 2 meeting pvh": "Meeting",
    "metrics/schedule/wip mgmt": "Metrics & Schedule",
    "fwyt/heijunka population": "Metrics & Schedule",
    "audit prep meeting":"Audit",
    "wip report issue troubleshooting with jb": "IT Issue/Update",
    "proformas sent out":"Proforma",
    "scheduling/wip mgmt.": "Metrics & Schedule",
    "training on clinical files, signed off on clinical files crdn and pvh": "Training/Mentoring",
    "emails, fwt, deco training": "Email & IM",
    "deco training, sha lab meeting": "Training/Mentoring",
    "email tier": "Email & IM",
    "grad dmaic training": "DMAIC",
    "emails, fwt, observing product analysi": "Email & IM",
    "reading through deco job aid, live case video": "Training/Mentoring",
    "lab meeting, reading sh product document": "Meeting",
    "training anne on clinical files for crdn & pvh": "Training/Mentoring",
    "meetings - sha weekly & 1": "Meeting",
    "email, fwt, cornerstone": "Email & IM",
    "emails, issues with excel, conerstone": "Email & IM",
    "emails, fw,": "Email & IM",
    "email, cornerstone": "Email & IM",
    "admin, email": "Email & IM",
    "after holidays emails.": "Email & IM",
    "meeting, computer issue": "Meeting",
    "lab meeting & tl meeting": "Meeting",
    "rewritting a lost file and computer issue": "IT Issue/Update",
    "meetings (harmony capa & pmpa/r&d call)": "Meeting",
    "morning admin (catching up after christmas)":"Admin",
    "issues with vision system": "IT Issue/Update",
    "trying to resolve my excel": "IT Issue/Update",
    "fw tool, email": "Email & IM",
    "pmpa meeting":"PMPA",
    "email and information about prevail file": "Email & IM",
    "email fwt": "Email & IM",
    "discussion with fola on nellcor returne":"Collaboration",
    "deco training": "Training/Mentoring",
    "1:1meeting":"Meeting",
    "emails, fwt": "Email & IM",
    "emails 30": "Email & IM",
    "fw tool, emails ect": "Email & IM",
    "conerstone":"Cornerstone",
    "mentoring/prep": "Training/Mentoring",
    "misc":"Admin",
    "1s meetings complex event consult emails/admin": "Meeting",
    "literature/readcube meeting": "Meeting",
    "aging wip":"Aged WIP Review",
    "aging file review":"Aged WIP Review",
    "report request/call": "Meeting",
    "town hall": "Meeting",
    "aem":"Meeting",
    "aem cqs meting":"Meeting",
    "scrum &call": "Scrum & Action",
    "it ticket/call": "IT Issue/Update",
    "loa catchup, it issues, meetings, email/admin, ng": "IT Issue/Update",
    "email & iml" : "Email & IM",
    "crdn call":"Meeting",
    "audit meeting": "Audit",
    "scrum": "Scrum & Action",
    "biohazrd kit approval": "Biohazard Kits Approval",
    "cas report": "Team Report",
    "knowledge sharing meeting/prep": "Meeting",
    "aged file/gemba review": "Gemba",
    "it issue": "IT Issue/Update",
    "pmq pre-meeting review q's":"PMQ Meeting",
    "pmq cr meeting":"PMQ Meeting",
    "pmq cr post-meeting action":"PMQ Meeting",
    "pmq cr fu email":"Email & IM",
    "pmq meeting":"PMQ Meeting",
    "infolding response meeting": "Meeting",
    "ti meeting": "Meeting",
    "tl meeting": "Meeting",
    "email/admin": "Email & IM",
    "emails admin": "Email & IM",
    "emails/admin": "Email & IM",
    "enails/admin": "Email & IM",
    "ms meeting": "Meeting",
    "aem + townhall":"Meeting",
    "team meeting":"Meeting",
    "townhall":"Meeting",
    "meeting prep":"Meeting",
    "training/meeting": "Training/Mentoring",
    "reg inquirie": "RI",
    "training with natalie": "Training/Mentoring",
    "training w/ natalie": "Training/Mentoring",
    "independent training": "Training/Mentoring",
    "idenpendent training": "Training/Mentoring",
    "cross functional meeting": "Meeting",
    "weekly ttvr/tmvr meeting": "Meeting",
    "staff meeting": "Meeting",
    "aems + townhall": "Meeting",
    "aem +town hall": "Meeting",
    "aems +town hall": "Meeting",
    "email; training; computer repair":"Email & IM",
    "team meetin": "Meeting",
    "proformas x":"Proforma",
    "aems +townhall": "Meeting",
    "ccrum/meeting": "Meeting",
    "crossfunctional meeting": "Meeting",
    "cross functional meeting": "Meeting",
    "cross funtional meeting":"Meeting",
    "scrumber":"Scrum & Action",
    "aem+townhall": "Meeting",
    "aems+townhall":"Meeting",
    "training qa": "Training/Mentoring",
    "ooo/appt": "OOO",
    "pmpa requests/update": "PMPA",
    "pmpa questions/request": "PMPA",
    "pmp questions/update": "PMPA",
    "pmpa question": "PMPA",
    "scrume" : "Scrum & Action",
    "gfe fax": "GFE",
    "gfe e-mail":"GFE",
    "questions/update": "Questions",
    "scurm": "Scrum & Action",
    "training/mentoring": "Training/Mentoring",
    "independednt cos": "COS",
    "meeting other": "Meeting",
    "pmq query":"PMQ Meeting",
    "reliant training":"Training/Mentoring",
    "training":"Training/Mentoring",
    "on":"Meeting",
    "lab meetig":"Meeting",
    "sh&a meeting":"Meeting",
    "tier 2 pvh":"Meeting",
    "tier 2 meeting crdn":"Meeting",
    "metrics/schedule/scrum, code gov, malf matrix update": "Scrum & Action",
    "sha Meeting":"Meeting",
    "rpa lab monthly meeting": "RPA Meeting/Action",
    "rpa lab": "RPA Meeting/Action",
    "nellcor meeting with julio - decision?":"Meeting",
    "monthly lab meeting":"Meeting",
    "tier 2 meeting;":"Meeting",
    "tier 2 meeting":"Meeting",
    "grad project meeting":"Meeting",
    "meeting majella aurelie":"Meeting",
    "quality aem":"Meeting",
    "emails ft": "Email & IM",
    "email To cell, setup": "Email & IM",
    "cornerstone training":"Training/Mentoring",
    "cornerstone / classroom training":"Training/Mentoring",
    "pmpa/r&d meeting":"PMPA",
    "scrum 30": "Scrum & Action",
    "scrum/meeting": "Scrum & Action",
    "training (on-boarding, product training, etc)":"Training/Mentoring",
    "blockers (it issues, gch issues, computer updates)": "IT Issue/Update",
    "scum": "Scrum & Action",
    "it update": "IT Issue/Update",
    "documentation reading": "Documentation",
    "sha meeting":"Meeting",
    "email to cell": "Email & IM",
    "email to cell, setup": "Email & IM",
    "gch issue": "IT Issue/Update",
    "escalated call":"Meeting",
    "set-up":"Set Up",
    "setup":"Set Up",
    "clinical safety plan review":"Clinical Safety Plan",
    "tl call on complex file":"Meeting",
    "other (please specify)":"Other",
    "other - please specify":"Other",
    "signal review":"Technical Assessment And Post Market Meetings, Peic Updates, Signal Review",
    "technical assessment and post market meetings, peic update":"Technical Assessment And Post Market Meetings, Peic Updates, Signal Review",
    "other-please specify":"Other",
    "other- please specify":"Other",
    "out of office":"OOO",
    "2 paid 15 min":"Break",
    "classroom training (d2d, emea, etc)":"Training/Mentoring",
    "trainer/ mentor (development and delivery)":"Training/Mentoring",
    "reading training material":"Training/Mentoring",
    "collaboration (i.e. file discussion)":"Collaboration",
    "flex team support": "Other Team WIP",
    "csf/ae/mazor support": "Other Team WIP",
    "qs":"Question",
    "extra ftq meeting":"Meeting",
    "performing qa, ml review":"QA",
    "qa meeting":"QA",
    "email; meetings; dataset comparison": "Email & IM",
    "emails admin scrumb": "Email & IM",
    "practice letters":"Training/Mentoring",
    "letter training":"Training/Mentoring",
    "training, collaboration":"Training/Mentoring",
    "training related activities":"Training/Mentoring",
    "training related activities (meet, review, questions, updates, finish inbox)":"Training/Mentoring",
    "scrum/metrics/schedule": "Metrics & Schedule",
    "metrics/schedule/scrum": "Metrics & Schedule",
    "weekly kpi email": "Metrics & Schedule",
    "rpa emails, ftq meeting": "RPA Meeting/Action",
    "practice letters, collaboration": "Collaboration",
    "rpa email": "RPA Meeting/Action",
    "rpa call": "RPA Meeting/Action",
    "collaboration/question": "Collaboration",
    "team collaboration": "Collaboration",
    "extra ftq meeting, rpa request":"Meeting",
    "1 hour training meeting":"Training/Mentoring",
    "and admin":"Admin",
    "shipping to plexus (liberant) : 30 min":"shipment",
    "spyral devices for shipping":"shipment",
    "affera training, rpa email request":"Training/Mentoring",
    "affera training, rpa email":"Training/Mentoring",
    "90 minutes training call":"Training/Mentoring",
    "r&d meeting":"Meeting",
    "quality day prep meeting":"Meeting",
    "affera training for sean & golden":"Training/Mentoring",
    "training related activity":"Training/Mentoring",
    "reading investigation document":"Documentation",
    "sh meeting (30) (calibrations docs & training paperwork (30)":"Meeting",
    "risk management recording":"Meeting",
    "quality day volunteering meeting":"Meeting",
    "training questions. comm/task/rr practice review":"Training/Mentoring",
    "affera training":"Training/Mentoring",
    "training + scrum":"Training/Mentoring",
    "questions, grading rr/comm/task practice":"Training/Mentoring",
    "questions, yellow belt":"Question",
    "other meeting":"Meeting",
    "mmo tuv audit - complaint list prep":"Audit",
    "event update/training email": "Email & IM",
    "1 hour training call":"Training/Mentoring",
    "1 hour training":"Training/Mentoring",
    "training prep":"Training/Mentoring",
    "cidex order with deni":"Ordering",
    "monthly meeting, admin, aortic meeting":"Meeting",
    "live case video, emails, sha meeting":"Reviewing Documents & Case Video",
    "cornerstone, live case video":"Cornerstone",
    "emails, training":"Training/Mentoring",
    "helping catherine ship valves, training":"Training/Mentoring",
    "scrum: 20.":"Scrum & Action",
    "scrum/team meeting":"Scrum & Action",
    "grad project report":"Project Work",
    "dmaic research":"Problem Solving",
    "cornerstone, analysis training":"Cornerstone",
    "define of dmaic":"Problem Solving",
    "ohs survey: 15 min":"Admin",
    "monthly meeting, emails, getting a device fron archive, additional photo":"Meeting",
    "emails, live case video": "Email & IM",
    "reviewing files (training sign off) changin dhr tasks to oem/cm and completing oem/cm form":"WIP Review",
    "monthly meeting & training file":"Meeting",
    "meetings - lab monthly and aortic":"Meeting",
    "morning admin and crdn team meeting":"Admin",
    "emails, admin, gemba walk etc.": "Email & IM",
    "fwt sheets prep, emails, cornerstone": "Email & IM",
    "emails, finding work tool, trying to figure the correct lot number": "Email & IM",
    "deco tidy up+montly meeting":"Meeting",
    "reviewing document":"Documentation",
    "dmaic fixing define after meeting in the morning":"Problem Solving",
    "emails surrounding activa sc and gathering information for this shipment": "Email & IM",
    "emaills, pulling fw tool, updating dhr tasks to oem and filling out oem sheet": "Email & IM",
    "pdp + pdp meeting":"Meeting",
    "lab team meeting":"Meeting",
    "sh/a meeting, prepping archive pallet":"Meeting",
    "reviewing files from training, meeting,":"Training/Mentoring",
    "reading catheter work instruction":"Documentation",
    "meeting, ellipsys dhr completing and uploading.":"Meeting",
    "file rework for cell and pvh meeting":"Meeting",
    "meeting, fire alarm":"Meeting",
    "fedex shipment enquiry":"Question",
    "emails, creating dec heijunka, change order,": "Email & IM",
    "finding work tool, reading agile document":"Admin",
    "live case videos, reading agile document":"Admin",
    "finding work tool, emails, training":"Admin",
    "cleaning after deco, emails, list of devices, ehs":"Admin",
    "cleaning aftr deco":"Admin",
    "training dcb":"Training/Mentoring",
    "liberant meeting and troubleshooting program issue":"Training/Mentoring",
    "liberant troubleshooting": "IT Issue/Update",
    "finalising job aid":"Documentation",
    "ehs training":"Training/Mentoring",
    "gch training":"Training/Mentoring",
    "opening and analysing sh&a devices for training":"Training/Mentoring",
    "training, lab shadowing":"Training/Mentoring",
    "training, reading past write-up":"Training/Mentoring",
    "training. lab shadowing":"Training/Mentoring",
    "training, write up shadowing":"Training/Mentoring",
    "spider documentation reading":"Documentation",
    "crdn related file remediation":"Remediation",
    "spider report reading":"Documentation",
    "training - breaking down sh/a devices with trainee":"Training/Mentoring",
    "reading past audit write ups":"Audit",
    "cm clinic & gch issue": "IT Issue/Update",
    "admin, shipping to nellcor and cornerstone":"Admin",
    "fw": "Metrics & Schedule",
    "looking over aortic device diagram":"Documentation",
    "ms office downtime, raised ticket": "IT Issue/Update",
    "shipping valve":"shipment",
    "shipment":"shipment",
    "reading aortic document":"Documentation",
    "training eugene on dcb":"Training/Mentoring",
    "training docs sign off'":"Training/Mentoring",
    "crdn kaizen":"Kaizen",
    "voyager transfer meeting":"Meeting",
    "onboarding new hire":"Training/Mentoring",
    "shippment issue":"shipment",
    "crdn kaizan meeting":"Kaizen",
    "15 (fw) 15 (emails) 30 (qch) 60 (amex card report)":"Admin",
    "cornerstone, fed ex shipping issues (website problems)":"Cornerstone",
    "audit prep (calibrations) and diamond temp equipment":"Audit",
    "cornerstone, admin":"Cornerstone",
    "fwt admin":"Admin",
    "sustainability tracker":"Admin",
    "mornign admin":"Admin",
    "change order document":"Change Order",
    "kaizen information":"Kaizen",
    "fwt and work for kaizen":"Kaizen",
    "call with it fixing zscaler": "IT Issue/Update",
    "minnesota shipping issue":"shipment",
    "shipping issue":"shipment",
    "ordering bi lauchpad from it portal": "IT Issue/Update",
    "fw & email": "Email & IM",
    "moving valves to return kit":"Admin",
    "correcting a reopened file":"Rework",
    "assist catherine with shipping issue":"shipment",
    "admin and shipping (denis)":"shipment",
    "computer issues, update and restart": "IT Issue/Update",
    "correct mfg site in gch": "IT Issue/Update",
    "sorting gch issue": "IT Issue/Update",
    "meetings - crdntier":"Meeting",
    "bcu meeting prep":"Admin",
    "laptop not right, keeps crashing on word": "IT Issue/Update",
    "cm clinic + gch issue": "IT Issue/Update",
    "observing harmony analysi":"Documentation",
    "erp capa office hourse":"CAPA",
    "dt catheter search for dt meeting next week.":"Meeting",
    "uploading vs dhr to gch and requesting new dhr from harmac filing out dhr from ect":"Admin",
    "job aid":"Documentation",
    "ohs meeting":"Meeting",
    "setting equipment up on sap/meeitng":"Meeting",
    "fwt email": "Metrics & Schedule",
    "reviewing documents & case video":"Reviewing Documents & Case Video",
    "complex crdn file":"WIP Review",
    "quality day meeting":"Meeting",
    "& change order":"Change Order",
    "change order for dt":"Change Order",
    "admin & re-location for ring gauges docs (showing eugene)":"Admin",
    "grad project":"Project Work",
    "training, ohs appointment":"Training/Mentoring",
    "lab shadowing, training":"Training/Mentoring",
    "observing aortic pa":"Training/Mentoring",
    "admin and cornerstone":"Admin",
    "reading through aortic manual":"Documentation",
    "qch & reviewing qa finding":"QA",
    "bi launchpad access and issue": "IT Issue/Update",
    "quality finding":"QA",
    "reading through dmaic slide":"Problem Solving",
    "self traing":"Training/Mentoring",
    "setting equipment up on sap and creating pm'": "IT Issue/Update",
    "customs issue":"Admin",
    "emails+shipping": "Email & IM",
    "sh&a lab review tier":"Meeting",
    "tier 2 meeting crdn & pvh":"Meeting",
    "docusign":"Admin",
    "angile":"Agile",
    "admin, cornerstone, tergazyme correction with denis & chemical check with myle":"Admin",
    "lab check for audit":"Audit",
    "capa meeting and quiz completion":"CAPA",
    "morn. admn, fwt":"Admin",
    "valve shipment":"shipment",
    "sorting through aged files on the heat map to see which ones can be processed as npr'":"Admin",
    "admin, sap gui installation":"Admin",
    "aortic risk management meeting":"Meeting",
    "emails+closurefast querie":"Question",
    "fwt, lab, admin":"Admin",
    "r&d support - stedi hyperacre":"Hypercare",
    "requesting bi launchpad access and sap reactivation access": "IT Issue/Update",
    "reading through agile doc":"Documentation",
    "(fai code meeting)":"Coding",
    "evolut tmv support":"Collaboration",
    "sh r&d call":"Meeting",
    "grad clinic":"Admin",
    "bi launchpad access/global reporting access": "IT Issue/Update",
    "equipment location change training with scott":"Training/Mentoring",
    "knowledge share recording":"Meeting",
    "emails+cornerstone": "Email & IM",
    "emails, tickets to remove inappropriate training": "Email & IM",
    "emails- image review": "Email & IM",
    "ciara meeting":"Meeting",
    "admin (calibration issue) + marmar rch q & a":"Admin",
    "chemical stock check":"Admin",
    "reading heli-fx redline":"Redline",
    "reading through stedi document":"Documentation",
    "aortic cross functional meeting":"Meeting",
    "conerstone/sap access": "IT Issue/Update",
    "main saver system slow. tl meeting": "IT Issue/Update",
    "meeting (dt transfer)":"Meeting",
    "quality meeting":"Meeting",
    "reading aortic coding doc":"Documentation",
    "rdn redline":"Redline",
    "printer issue": "IT Issue/Update",
    "crdn tier":"Meeting",
    "sh tier":"Meeting",
    "shipping device":"shipment",
    "going through traing file":"Training/Mentoring",
    "lab tour with grad project group":"Tour",
    "cm clinic prep":"Admin",
    "1:1 meeting":"Meeting",
    "1:1 (including ad-hoc)":"Meeting",
    "& change order update":"Change Order",
    "giving lab tour to project group member":"Tour",
    "emails + cornerstone": "Email & IM",
    "lab and ehs audit":"Audit",
    "sha tier 2":"Meeting",
    "laptop update restart": "IT Issue/Update",
    "requesting approvers to approbe office desktop app": "IT Issue/Update",
    "tier 2":"Meeting",
    "mfg meeting":"Meeting",
    "morning admn":"Admin",
    "emails- sap access": "Email & IM",
    "housekeeping of gloves in kanban":"Admin",
    "emails 15": "Email & IM",
    "call for change order":"Change Order",
    "emial": "Email & IM",
    "emai": "Email & IM",
    "connection issue": "IT Issue/Update",
    "dmaic training":"Problem Solving",
    "supporting":"Collaboration",
    "kaizen follow up":"Kaizen",
    "clinical call":"Meeting",
    "meetings On liberant issue":"Meeting",
    "shiperp meeting":"Meeting",
    "eod uat call":"Meeting",
    "admin + cornerstone":"Admin",
    "training, gch access troubleshooting":"Training/Mentoring",
    "analysis training reading":"Training/Mentoring",
    "training, spyder and closurefast documentation reading":"Training/Mentoring",
    "training, gch troubleshooting, spider analysis prep":"Training/Mentoring",
    "fwt":"Admin",
    "morning admin, meeting with scott":"Admin",
    "project meeting":"Meeting",
    "sorting work journal for uni":"Documentation",
    "updating the list of sh valve":"Documentation",
    "uat 'sign-off'":"UAT",
    "uat shiperp session - product complaint":"UAT",
    "reading through endurant ifu":"Documentation",
    "inpact 018 x1 meeting":"Meeting",
    "on line training inpact 018 x1":"Training/Mentoring",
    "change order update":"Change Order",
    "audti prep":"Audit",
    "town hall recording":"Meeting",
    "admin and dt presentation set up (slide decks - deco process)":"Admin",
    "sorting aged file":"Aged File Review",
    "shiperp recording":"Meeting",
    "reading through shiperp document":"Documentation",
    "spider device documentation reading":"Documentation",
    "training reading":"Training/Mentoring",
    "spider archive and documentation reading":"Documentation",
    "eod uat meeting and discussion afterwards with myle":"Meeting",
    "feedback reading from analysi":"Feedback",
    "dt presentation recording":"Admin",
    "meeting with anne":"Meeting",
    "shiperp issues, lost access": "IT Issue/Update",
    "meetings on liberant issue":"Meeting",
    "meeting crdn & pvh":"Meeting",
    "organising shiperp info for afternoon call":"Meeting",
    "reviewing spider complaint code":"Coding",
    "shiperp catch up meeting":"Meeting",
    "update meeting with aurelie":"Meeting",
    "meeting with pat":"Meeting",
    "catch up meeting with aurelie.":"Meeting",
    "archive box issue": "Email & IM",
    "admin after shiperp meeting":"Admin",
    "admin,":"Admin",
    "shiperp meeting discussion with myles (re-running test environment)":"Collaboration",
    "inpact 018 x1 meeting":"Meeting",
    "crdn email about dhr": "Email & IM",
    "meeting with matthew":"Meeting",
    "on line training inpact 018 x1":"Meeting",
    "sha slide":"Admin",
    "getting data for meeting":"Meeting",
    "crdn complaint call":"Meeting",
    "spider feedback question":"Feedback",
    "pvh meeting catch up":"Meeting",
    "computer restart and update": "IT Issue/Update",
    "cornerstone and email":"Cornerstone",
    "audit prep - labelling":"Audit",
    "it iissue": "IT Issue/Update",
    "x tier":"Meeting",
    "archive issues+email": "Email & IM",
    "inpact 0.18 meeting":"Meeting",
    "meeting with cell":"Meeting",
    "change order querie":"Question",
    "helping colleague":"Collaboration",
    "training videos, live case video":"Reviewing Documents & Case Video",
    "watching live video":"Reviewing Documents & Case Video",
    "end of week admin":"Admin",
    "vaccine, live case video":"Reviewing Documents & Case Video",
    "emails, finding work tool, reading agile document": "Email & IM",
    "shipping valves, training":"Training/Mentoring",
    "fwt, cornerstone training":"Training/Mentoring",
    "reviewing documents & case video":"Reviewing Documents & Case Video",
    "cornerstone, emails, etc":"Cornerstone",
    "change order creation for pvh test method":"Change Order",
    "prep for presentation":"Admin",
    "fwt, admin for crdn":"Admin",
    "training cornerstone":"Training/Mentoring",
    "emails, finding work tool, getting my gch fixed.": "Email & IM",
    "emails checking deco chemicals shipping": "Email & IM",
    "it issues, meeting": "IT Issue/Update",
    "emails cell replies tier": "Email & IM",
    "cornerstone, emails, admin":"Cornerstone",
    "discussing complex file, pullng haz/fai codes for ana":"Training/Mentoring",
    "helping colleagues and emails. sorting through crdn list of devices that are expected":"Collaboration",
    "emails, pvh change order update, ohs update": "Email & IM",
    "emails, lab set up, closing file, it issue": "Email & IM",
    "shipping, meeting":"Meeting",
    "emails, discussing dhr tasks, finding work tool": "Email & IM",
    "emails, cleaning after deco, packing device": "Email & IM",
    "emails surrounding shipments, review of presentation and resolving issues from cell team.": "Email & IM",
    "emails, admin, finding work tool": "Email & IM",
    "emails, finding work tool, working on reopened file, lab set up": "Email & IM",
    "emails, fonding work tool, cornerstone": "Email & IM",
    "emails, finding work tool, closing reopened file": "Email & IM",
    "change order":"Change Order",
    "follow up emails, manuals, ohs action plan.": "Email & IM",
    "email, packing devices, cleaning after lab analysi": "Email & IM",
    "calls - crdn cell and santa ana":"Meeting",
    "aortic mfg assessment and fume hood fix with workshop":"Mfg Assessment",
    "emails, fwt, crdn question": "Email & IM",
    "1-1 meeting":"Meeting",
    "emails finding work requests from the cell": "Email & IM",
    "crdn meeting and morning admin":"Admin",
    "admin (emails, teams messages etc)":"Admin",
    "emails, team": "Email & IM",
    "emails, fw tool ect": "Email & IM",
    "emails, fw ect": "Email & IM",
    "email for manufacturing assessment": "Email & IM",
    "emails fwt": "Email & IM",
    "emails, cornerstone": "Email & IM",
    "tier 2 crdn":"Meeting",
    "tier":"Meeting",
    "manufacturing assessment meeting.":"Mfg Assessment",
    "looking over change order":"Change Order",
    "ordering cidex from warehouse":"Ordering",
    "workshop email": "Email & IM",
    "tier 2 meeting pvh & 1x cornerstone":"Meeting",
    "sh mfg meeting":"Meeting",
    "supporting workshop - fumehood sash":"Next Gen",
    "workshop request":"Next Gen",
    "finishing up pdp and work summary form with signatures etc and getting printed/scanned":"Admin",
    "sh mfg assessment":"Mfg Assessment",
    "emails, chaning dhr tasks to oem cm tasks and completing and attaching the oem cm form": "Email & IM",
    "emails admin tier": "Email & IM",
    "lab montly meeting":"Meeting",
    "finding work, emails etc, it issue": "Metrics & Schedule",
    "emails, finding work tool, lab set up, reopened file, additional photo": "Email & IM",
    "emails, pulling fw tool, updating dhr tasks to oem and filling out oem sheet": "Email & IM",
    "emails, cornerstone training": "Email & IM",
    "reviewing files and opening dhr tasks for cf as part of xmass burn down":"WIP Review",
    "meeting, ellipsys dhr completing and uploading,":"Meeting",
    "bagging devices + email": "Email & IM",
    "emails, fwt, crdn tracker": "Email & IM",
    "morning admin email":"Admin",
    "emails dealing with cryocath products returned in error": "Email & IM",
    "emails, finding work, lab set up": "Email & IM",
    "email, finding work tool, lab set up,": "Email & IM",
    "e-mails, cornerstone": "Email & IM",
    "meeting mfg":"Meeting",
    "meeting with ciara re christmas burndown":"Meeting",
    "dmaic meeting with lisa":"Problem Solving",
    "emails about the sending the product": "Email & IM",
    "emails, admin, etc": "Email & IM",
    "emails, finding work tool, set up the lab": "Email & IM",
    "nelcor meeting":"Meeting",
    "follow up email": "Email & IM",
    "emails, heijunka ect": "Email & IM",
    "emails, fw, im'": "Email & IM",
    "emails and im regarding crdn tracker": "Email & IM",
    "emails, desk booking, admin etc": "Email & IM",
    "meeting, email": "Email & IM",
    "training file for eugene":"Training/Mentoring",
    "pulling fw tool and email": "Metrics & Schedule",
    "finding work, morning admin etc": "Metrics & Schedule",
    "traing file for laura":"Training/Mentoring",
    "cidex ordering. tergazyme/ virkon quote":"Ordering",
    "cidex ordering":"Ordering",
    "35 mins reverse-shadowing":"Training/Mentoring",
    "cornerstone, scrum":"Cornerstone",
    "cornerstone,":"Cornerstone",
    "training and staff meeting":"Training/Mentoring",
    "60 minute training meeting":"Training/Mentoring",
    "training and meeting":"Training/Mentoring",
    "affera training, rpa collaboration":"Training/Mentoring",
    "trainings, practice rr":"Training/Mentoring",
    "training and question":"Training/Mentoring",
    "training reviews, explanation":"Training/Mentoring",
    "training, keytext for letters, collaboration":"Training/Mentoring",
    "training meeting and staff meeting":"Training/Mentoring",
    "affera training prep":"Training/Mentoring",
    "training/question":"Training/Mentoring",
    "training and collaboration":"Training/Mentoring",
    "1 hr 15 mins training":"Training/Mentoring",
    "scrum, email": "Email & IM",
    "oem integer meeting":"Meeting",
    "affera meeting":"Meeting",
    "affera ftq meeting":"Meeting",
    "affera mpxr meeting":"Meeting",
    "admin/email": "Email & IM",
    "emails, collaboration with lab": "Email & IM",
    "practice":"Training/Mentoring",
    "comm, task practce":"Training/Mentoring",
    "prism 2 training":"Training/Mentoring",
    "extra ftq meeting":"Meeting",
    "ris": "RI",
    "meetings; email": "Meeting",
    "training independent": "Training/Mentoring",
    "ad hoc ri data request from pmpa": "PMPA",
    "emails/adming":"Email & IM",
    "meetings other": "Meetings",
    "tm trainer":"Training/Mentoring",
    "emails qa scrumb":"Email & IM",
    "pmpa question/update": "PMPA",
    "cos1 training":"Training/Mentoring",
    "ooo for appt": "OOO",
    "emails/question": "Question",
    "questions/discussion": "Question",
    "training product training team meeting cross functional meeting aems + townhall":"Training/Mentoring",
    "lit scrum metric":"Scrum & Action",
    "pvh aged file review":"Aged WIP Review",
    "pmq cr post-meeting q's review":"PMQ Meeting",
    "it issues over im and phone": "IT Issue/Update",
    "imdrf code call": "Meeting",
    "calls+": "Meeting",
    "cornerstone training / gap report / peb correction":"Cornerstone",
    "capa (owner & support)":"CAPA",
    "aged file":"Aged WIP Review",
    "intake meeting": "Meeting",
    "scrum & after scrum meeting":"Scrum & Action",
    "interruptions/question": "Question",
    "emails other": "Email & IM",
    "im's/email": "Email & IM",
    "it/admin": "IT Issue/Update",
    "mentoring":"Training/Mentoring",
    "mentoring/interruption":"Training/Mentoring",
    "traing":"Training/Mentoring",
    "complex/consult training":"Training/Mentoring",
    "meeting with tm":"Meeting",
    "sme improvement projects/ problem solving":"Problem Solving",
    "training, scrum":"Training/Mentoring",
    "team communication":"Meeting",
    "aem (justin for all brian, chris, geoff for ftes)": "Meeting",
    "respond to engineer email": "Email & IM",
    "training q":"Training/Mentoring",
    "training, practice, cornerstone":"Training/Mentoring",
    "ri meeting": "RI",
    "team meetings aems team building":"Meeting",
    "file escalations/ corrections (gap findings, fer escalations)":"WIP Review",
    "collaboration (i.e. file discussion)": "Collaboration",
    "fill out capacity management tools (heijunka, non-wip)": "Metrics & Schedule",
    "blockers (it issues, gch issues, computer updates)": "IT Issue/Update",
    "coding updates related meeting":"Coding",
    "trainer/ mentor (development and delivery)":"Training/Mentoring",
    "run wr/ heijunka": "Metrics & Schedule",
    "performing qa":"QA",
    "ri work": "RI",
    "questions, death event rr/notification":"Question",
    "training letter burdown": "Letter Burndown",
    "team collaboration repsonded to": "Collaboration",
    "collaboration with other groups (i.e. s&r, regions, pats)": "Collaboration",
    "issues with laptop": "IT Issue/Update",
    "meeting on file":"Meeting",
    "tm meeting":"Meeting",
    "gch crashing": "IT Issue/Update",
    "software update": "IT Issue/Update",
    "gch crashe": "IT Issue/Update",
    "pc restart": "IT Issue/Update",
    "gch slow and crashing": "IT Issue/Update",
    "call with tl on file":"Meeting",
    "tl call on file":"Meeting",
    "it issues/restart": "IT Issue/Update",
    "pc restart/update": "IT Issue/Update",
    "training louise": "Training/Mentoring",
    "cornerstone scrum":"Cornerstone",
    "louise training": "Training/Mentoring",
    "audit prep": "Audit",
    "audit support fda ri review": "Audit",
    "teams meeting":"Meeting",
    "it/computer issue": "IT Issue/Update",
    "lab meeting":"Meeting",
    "grad project work":"Project Work",
    "lab shadowing": "Training/Mentoring",
    "shadowing aortic pa": "Training/Mentoring",
    "fire marshall training": "Training/Mentoring",
    "it issue/update": "IT Issue/Update",
    "workday career development":"Career Development",
    "rfai call": "Meeting",
    "morning admin": "Admin",
    "lab monthly meeting project work":"Project Work",
    "meetings voyager transfer":"Meeting",
    "reading previous investigation write ups/consulting documentation": "Documentation",
    "admin and catheter tracking for nellcor": "Admin",
    "lab monthly meeting" :"Meeting",
    "aortic meeting" :"Meeting",
    "it": "IT Issue/Update",
    "aortic report": "Team Report",
    "sh report": "Team Report",
    "pvh report": "Team Report",
    "pmpa":"PMPA",
    "pmq querie": "PMQ Meeting",
    "next gen meeting":"Next Gen",
    "new ri":"RI",
    "it support": "IT Issue/Update",
    "rrtt report update": "RRTT",
    "pmpa questions/updat":"PMPA",
    "pvh call": "Meeting",
    "aging file": "Aged WIP Review",
    "is tool": "IS Tool Review",
    "srcum": "Scrum & Action",
    "readcube meeting":"Meeting",
    "readcube training": "Training/Mentoring",
    "vig training call": "Training/Mentoring",
    "pmq follow-up": "PMQ Meeting",
    "global quality meeting":"Meeting",
    "meetings & action":"Meeting",
    "proforma meeting":"Meeting",
    "email/meeting action": "Email & IM",
    "dhr meeting":"Meeting",
    "sh proforma training":"Training/Mentoring",
    "bsi audit report": "Audit",
    "aging": "Aged WIP Review",
    "pmq cr meeting & action":"PMQ Meeting",
    "pmq coding query":"PMQ Meeting",
    "aortic call":"Meeting",
    "gemba&prep": "Gemba",
    "one to one": "Meeting",
    "inv summ review": "IS Tool Review",
    "scrum, cornerstone":"Scrum & Action",
    "actions from scrum/minute":"Scrum & Action",
    "scrum, emails, meeting":"Scrum & Action",
    "knowledge sharing call": "Meeting",
    "pmq call":"PMQ Meeting",
    "pmq follow up":"PMQ Meeting",
    "ri review":"RI",
    "sh call": "Meeting",
    "sh vig meeting": "Meeting",
    "eu mdr call": "Meeting",
    "other emails & im":"Email & IM",
    "pmq mfg assessment call": "PMQ Meeting",
    "sh vig review/querie": "Question",
    "aged wip review": "Aged WIP Review",
    "file review": "Aged WIP Review",
    "rpa meeting": "RPA Meeting/Action",
    "rpa meeting and action": "RPA Meeting/Action",
    "fer capa report/review": "CAPA",
    "rpa meeting/action": "RPA Meeting/Action",
    "rpa meeting & action": "RPA Meeting/Action",
    "vig training": "Training/Mentoring",
    "laptop update": "IT Issue/Update",
    "laptop setup": "IT Issue/Update",
    "ivanti connection issue": "IT Issue/Update",
    "call with it":"IT Issue/Update",
    "it call":"IT Issue/Update",
    "gemba prep":"Gemba",
    "pmq query review":"PMQ Meeting",
    "ri update/submit":"RI",
    "pmpa questions/update":"PMPA",
    "precedent event/rd conflict": "RD Conflict",
    "rd conflict": "RD Conflict",
    "kickouts/hypercare":"Hypercare",
    "pmpa request":"PMPA",
    "discussions/chat":"Collaboration",
    "office discussions/q&a session":"Collaboration",
    "discussion":"Collaboration",
    "pmpa update":"PMPA",
    "pmpa/questions/update":"PMPA",
    "intrepid ?'s":"Question",
    "email; meeting": "Email & IM",
    "email; training": "Email & IM",
    "emails/amin": "Email & IM",
    "email; article reivew for svt": "Email & IM",
    "email admin": "Email & IM",
    "rpa action": "RPA Meeting/Action",
    "rpa minutes write-up":"RPA Meeting/Action",
    "complex events consult": "Complex Event Consult",
    "email": "Email & IM",
    "codes governance call":"Meeting",
    "navion call":"Meeting",
    "sh meeting/event review":"Meeting",
    "pvh audit report":"Audit",
    "email/im & call":"Email & IM",
    "sh meeting":"Meeting",
    "lsh bridge issue":"LSH Bridge",
    "audit support":"Audit",
    "aortic meeting & post meeting call":"Meeting",
    "adn career development workshop":"Career Development",
    "ng workshop, lates, wmail/admin": "Next Gen",
    "a whole lot of collaboration, meet and greets, meetings, troubleshooting, and training": "Collaboration",
    "scrum and call":"Scrum & Action",
    "ri follow-up":"RI",
    "ri completion":"RI",
    "ri call": "RI",
    "processing question":"Question",
    "meetings; pe review for pmpa":"PMPA",
    "emails/discussion":"Email & IM",
    "mtgs 2 hrs": "Meeting",
    "sales rep training": "Training/Mentoring",
    "mir training": "Training/Mentoring",
    "catching up on email from being ooo for":"Email & IM",
    "rs pxm sh inbox":"RS Inbox",
    "rs sh inbox":"RS Inbox",
    "cornerstone/it ticket": "IT Issue/Update",
    "it ticket/tech issue": "IT Issue/Update",
    "ad hoc request from pmpa":"PMPA",
    "cornerstone + it ticket": "IT Issue/Update",
    "emails/other":"Email & IM",
    "catch up on email":"Email & IM",
    "weekly tmvr clinical event investigation meeting": "Meeting",
    "on clinical. it tickets and cornerstone": "IT Issue/Update",
    "restore/mpxr issue/discussion": "IT Issue/Update",
    "weekly ttvr clinical event investigation meeting": "Meeting",
    "prep for audit":"Audit",
    "sh staff meet": "Meeting",
    "submitted nurse consult":"Nurse Consult",
    "contego hypercare":"Hypercare",
    "mns cornerstone":"Cornerstone",
    "qa observation":"QA",
    "qa finding":"QA",
    "ai upskilling":"Training/Mentoring",
    "qa assessment":"QA",
    "parklife meeting": "Meeting",
    "team leads meeting": "Meeting",
    "contego meeting": "Meeting",
    "coding call": "Meeting",
    "complaint call": "Meeting",
    "scrum/1:1 meeting": "Meeting",
    "scrum + training":"Training/Mentoring",
    "scrum/training":"Training/Mentoring",
    "scrum/cornerstone":"Scrum & Action",
    "team scrum":"Scrum & Action",
    "pmpa discussion/canada discussion":"PMPA",
    "discussions/im": "Email & IM",
    "skills lab + consult w/corie":"Nurse Consult",
    "computer updates/rebooting/comp problem": "IT Issue/Update",
    "weekly cqxm/pmpa meeting":"PMPA",
    "meetings; pe review for pmpa.":"PMPA",
    "ri discussion":"RI",
    "pmpa requests & qa":"PMPA",
    "pacemaker complaint meeting":"Meeting",
    "mn mentoring": "Training/Mentoring",
    "steam pop review, cas coding":"Coding",
    "audit, building a community/potluck & costume party":"Audit",
    "internal audit backroom support":"Audit",
    "internal audit backroom":"Audit",
    "in-person discussions/independent research for south africa fvr process":"Collaboration",
    "impromptu discussion":"Collaboration",
    "skills lab vlt":"Skills Lab",
    "tvtr discussion":"Collaboration",
    "ris/internal audit questions about ris":"Audit",
    "em/technology etc":"Em Etc",
    "other/em etc":"Em Etc",
    "impromptu in-person discussion":"Collaboration",
    "emails/inbox": "Email & IM",
    "emails/misc": "Email & IM",
    "leading indicators and meeting":"Meeting",
    "wip mgmt/pmpa":"PMPA",
    "call with rep":"Meeting",
    "teams chat": "Email & IM",
    "30: pmpa updates/discussion misc":"PMPA",
    "misc update": "IT Issue/Update",
    "leading indicators/meeting/action":"Meeting",
    "it issue/update": "IT Issue/Update",
    "it issues/tix": "IT Issue/Update",
    "emails/misc/technology": "IT Issue/Update",
    "teams question": "Email & IM",
    "ms teams Chats/interruption": "Email & IM",
    "emails/in-person discussion": "Email & IM",
    "cq problem solving monthly meeting":"Problem Solving",
    "leading indicators meeting":"Meeting",
    "jar lid particulate discussion":"Jar Lid Discussion",
    "emails/action": "Email & IM",
    "mir training meeting":"Training/Mentoring",
    "redline doc":"Redline",
    "extra time on inbox":"RS Inbox",
    "tm suppor":"Tm Support",
    "ia backroom support scrum":"Audit",
    "ia backroom support scrum audit meeting":"Audit",
    "weekly team meeting":"Meeting",
    "laptop issue": "IT Issue/Update",
    "agile co":"Agile Change Order",
    "slow gch": "IT Issue/Update",
    "ia backroom audit meeting":"Audit",
    "scrum: 30.":"Scrum & Action",
    "qms training":"Training/Mentoring",
    "srum,parklife":"Scrum & Action",
    "meetings: 60 (includes answering questions)":"Meeting",
    "scrum 20":"Scrum & Action",
    "ste up":"Set Up",
    "training review":"Training/Mentoring",
    "escalated call&prep":"Meeting",
    "call with monica":"Meeting",
    "audit, meeting":"Audit",
    "new desk set up":"Desk",
    "emails etc": "Email & IM",
    "misc/desk":"Desk",
    "misc/email": "Email & IM",
    "ris/south africa final rr request":"RI",
    "questions/misc":"Questions",
    "cornertsone":"Cornerstone",
    "pmpa disucssion":"PMPA",
    "crdn strategy meeting":"Meeting",
    "providing kirsty vig training":"Training/Mentoring",
    "escalations training":"Training/Mentoring",
    "train":"Training/Mentoring",
    "questions/email": "Email & IM",
    "emails/inbox/it issue": "Email & IM",
    "intrepid question":"Question",
    "email misc.": "Email & IM",
    "career development/inclusion plan":"Career Development",
    "email misc": "Email & IM",
    "training/mentor review":"Training/Mentoring",
    "clinical training":"Training/Mentoring",
    "harmony meeting":"Meeting",
    "weekly tmvr meeting":"Meeting",
    "emails/it issue": "Email & IM",
    "emails misc.": "Email & IM",
    "questions/emails/inbox": "Email & IM",
    "emails/etc": "Email & IM",
    "email wip etc.": "Email & IM",
    "emails/teams message": "Email & IM",
    "it/gch slowness": "IT Issue/Update",
    "questions/pmpa":"PMPA",
    "meeting/email": "Email & IM",
    "questions/pmpa inquirie":"PMPA",
    "leading indicators action/meeting":"Meeting",
    "unplanned nextgen":"Next Gen",
    "nextgen prep":"Next Gen",
    "team meetings, aems, team building, 1:1s, connect sessions":"Meeting",
    "clinical safety call":"Meeting",
    ""
    "tier 1 meeting crdn":"Meeting",
    "qd meeting":"Meeting",
    "aem recording":"Meeting",
    "inbox maintenance":"RS Inbox",
    "rs jax inbox support":"RS Inbox",
    "training (launcher)":"Training/Mentoring",
    "training (launcher curves)":"Training/Mentoring",
    "meetings - crdn t1 and voyager prep":"Meeting",
    "contacting r&d da for info":"Meeting",
    "email; meetings; collaboration": "Email & IM",
    "email admin scrumb": "Email & IM",
    "ran batchman for fer/fac":"Batchman",
    "' email":"Email & IM",
    "admin, setting up dcb hood":"Admin",
    "and cornerstone":"Cornerstone",
    "reg inquiries next gen support ooo metrics/schedule/wip mgmt":"RI",
    "collaboration audit support problem solving late mdrs qa clinical pmpa questions/update":"Audit",
    "emails admin etc": "Email & IM",
    "weekly tvr meeting":"Meeting",
    "collaboration sh/crm":"Collaboration",
    "pvh next gen meeting":"Next Gen",
    "gemba & prep":"Gemba",
    "proformas x2":"Proforma",
    "1s":"Meeting",
    "yellow belt cornerstone":"Yellow Belt",
    "yellow belt cornerstone, question":"Yellow Belt",
    "training qs":"Question",
    "ran batchman for fers/fac":"Batchman",
    "scheduling/wip mgmt": "Metrics & Schedule",
    "inbox/email": "Email & IM",
    "coordinating with pmpa":"PMPA",
    "emails wip etc": "Email & IM",
    "stragety meeting":"Meeting",
    "escalated call excel":"Meeting",
    "meeting with rep":"Meeting",
    "eu vig training":"Training/Mentoring",
    "training kirsty":"Training/Mentoring",
    "meeting with lab":"Meeting",
    "training + ri completion + chey wade email":"Training/Mentoring",
    "sr email": "Email & IM",
    "meeting on clinical study":"Meeting",
    "restart": "IT Issue/Update",
    "escalated call prep":"Meeting",
    "safety meeting":"Meeting",
    "computer reboot": "IT Issue/Update",
    "bsi audit meeting":"Audit",
    "it/tech issue": "IT Issue/Update",
    "pmpa discussion":"PMPA",
    "wip mgmt.":"WIP Mgmt",
    "weekly revalve meeting":"Meeting",
    "it ticket": "IT Issue/Update",
    "inbox":"RS Inbox",
    "technology": "IT Issue/Update",
    "late rr discussion":"Collaboration",
    "ng workshop, emails/admin, ms review": "Next Gen",
    "unplanned meetings, training/mentoring, unplanned questions/interruptions/people showing up at my desk with questions requiring research and collaboration": "Training/Mentoring",
    "ri repsonse":"RI",
    "rrt":"Rrtt",
    "cornerstone and admin":"Admin",
    "dmaic":"Problem Solving",
    "ng workshop, email/admin/collab": "Next Gen",
    "ng workshop, lates, email/admin": "Next Gen",
    "rpa":"RPA Meeting/Action",
    "on a call":"Meeting",
    "tier 2 pvh meeting":"Meeting",
    "tier2 / collective":"Meeting",
    "(fw 15) (emails 15) (looking at aged files 30) (cf files additional testing 30)": "Aged WIP Review",
    "meetings, ng/coding": "Next Gen",
    "crdn weekly call":"Meeting",
    "(meetings 60) looking at aged files to see if any of them are workable (60)":"Meeting",
    "parkmore townhall":"Meeting",
    "prep for meeting": "Admin",
    "on call":"Meeting",
    "(fw - 15) (emails -15)":"Email & IM",
    "aortic cross functional call":"Meeting",
    "shiperp go/no go call":"Meeting",
    "shiperp pro-forma vs commercial invoice call":"Meeting",
    "rdn emails for generator return":"Email & IM",
    "call on file":"Meeting",
    "collaboration, problem statement for yellow belt training":"Yellow Belt",
    "career development plan":"Career Development",
    "ng, meetings, event review": "Next Gen",
    "review affera materials with ruth for ftq/mpxr":"Meeting",
    "affera emails/prism 2 hypercare meeting":"Meeting",
    "ftq review meeting (extra time) 60":"Meeting",
    "emails/rpa requests/collaboration":"Collaboration",
    "team colaboration":"Collaboration",
    "training: questions & reviewing event": "Training/Mentoring",
    "affera ftq project":"Project Work",
    "ftq project":"Project Work",
    "metrics, scrum, training":"Scrum & Action",
    "training, collaboration, ide snack & chat": "Training/Mentoring",
    "affera rpa - emails/phone call": "RPA Meeting/Action",
    "metrics/scrum/schedule":"Scrum & Action",
    "affera rpa email": "RPA Meeting/Action",
    "closed several checked) mostly training activtie": "Training/Mentoring",
    "affera email":"Email & IM",
    "meetings, training, admin/emails, ms requests, rpa request":"Admin",
    "meetings, training/education, admin/emails, ms/rpa, collaboration":"Admin",
    "burndown meeting, metrics, schedule":"Admin",
    "gemba and prep, metrics, schedule":"Gemba",
    "computer issues, collaboration, training plan update": "IT Issue/Update",
    "meetings, metrics/schedule":"Meeting",
    "meetings, collaboration, admin/email, cornerstone":"Meeting",
    "phone call":"Meeting",
    "audit support - monitor backroom pull pesrs/reg reports =":"Audit",
    "emails, collaboration, rpa request":"Email & IM",
    "remediation activities 10 events reprocessed":"Remediation",
    "ng, regional, collaboration/event review, coding, email/admin, filling out pa board":"Next Gen",
    "internal audit pre-requests, audit review, affera email":"Audit",
    "training, ps event reviews, collaboration, meetings, emails/admin, filling out pa board":"Training/Mentoring",
    "rpa /trending/hypercare emails, phone calls, questions/collaboration,":"RPA Meeting/Action",
    "meetings, event reviews, collaboration, and a lot of time on the phone with my it besties working through loss of microsoft functionalitie":"Meeting",
    "ms, collaboration/event reviews, veteran's day program, emails/filling out pa board":"Email & IM",
    "ca rd audit":"Audit",
    "supp rr review practice events, emails - rpa, trending, audit":"Audit",
    "machine learning rd project request":"Project Work",
    "meetings, trending requests, ms and additional rds on friday report completed-this is wip but no proper category for it, filling out pa board":"Meeting",
    "figuring out how to undo-benefit selection and reapply when":"Admin",
    "training/review practice event":"Training/Mentoring",
    "scrum metrics, schedule for friday":"Scrum & Action",
    "scrum metrics, schedule for monday":"Scrum & Action",
    "delivery) practice1 letter":"Training/Mentoring",
    "benefit enrollment":"Admin",
    "rpa request":"RPA Meeting/Action",
    "project":"Project Work",
    "shadow":"Training/Mentoring",
    "trending team request":"Project Work",
    "training, collaboration, emails/admin":"Training/Mentoring",
    "meetings, collaboration, troubleshooting, training, email/admin":"Meeting",
    "meetings, late, traning, regional, emails/admin, collaboration":"Meeting",
    "precedent event review, training, meeting":"Training/Mentoring",
    "many meetings for collaboration, training time (delivery and receipt)":"Meeting",
    "meetings,collaboration, event review for potential capa, schedule metric":"Meeting",
    "meetings, lates and submission, collaboration, ms request, emails/admin":"Meeting",
    "emails - affera, rpa, hypercare":"Email & IM",
    "training, collaboration, pull work, scrum":"Training/Mentoring",
    "emails - rpa/audit, collaboration":"Email & IM",
    "emails, collaboration, metrics,":"Email & IM",
    "emails/teams - affera, rpa, audit, hypercare":"Email & IM",
    "collaboration (including rpa lab,)":"Collaboration",
    "training side work":"Training/Mentoring",
    "nextgen": "Next Gen",
    "flexcathcross breach meeting":"Meeting",
    "meetings, collaboration, troublehooting, training, email/admin":"Meeting",
    "monitoring audit backroom":"Audit",
    "email/teams - affera,rpa,mappers; collaboration":"Email & IM",
    "meetings, training, emails/admin":"Admin",
    "meetings, training, collaboration, emails/admin":"Admin",
    "collaboration, meetings, ps coding remediation, email/admin":"Meeting",
    "meetings, emails, schedule":"Email & IM",
    "emails/teams - rpa, collaboration":"Email & IM",
    "meetings, collaboration, ps coding remediation":"Meeting",
    "questions from team, collaboration":"Question",
    "scrum/ metrics/schedule":"Scrum & Action",
    "christmas burndown meeting 60 minute":"Meeting",
    "emails/rpa request/teams request":"Email & IM",
    "metrics, meetings, schedule":"Admin",
    "rpa requests, cornerstone":"RPA Meeting/Action",
    "burndown meeting":"Meeting",
    "emails, collaboration, rpa":"Email & IM",
    "practice letter": "Training/Mentoring",
    "audit support - monitor backroom pull pesrs/reg reports":"Audit",
    "audit support - pe search, pull pesrs, monitor backroom":"Audit",
    "completed pe (ftq) for audit":"Audit",
    "kick-off meeting for capa 605686 remediation activitie":"CAPA",
    "audit support - pesrs reg reports - total of":"Audit",
    "audit support - pull pesrs, monitor backroom":"Audit",
    "personal development plan":"Career Development",
    "career development review":"Career Development",
    "career developemnt plan":"Career Development",
    "training - event create, review, meet, question": "Training/Mentoring",
    "metrics, tl meeting, event request, meetings, ri":"Meeting",
    "consulting/email":"Email & IM",
    "getting training plans established, meetings scheduled, etc.":"Admin",
    "training took whole day, meetings went over, pulling training events took a while since training environment is having tech issues, many technical difficultie": "Training/Mentoring",
    "metrics, schedule, ri help":"Admin",
    "training, ml rd proj meeting, collaboration":"Training/Mentoring",
    "metrics, schedule, lab call, collaboration, training event review, data pull":"Admin",
    "1.5 hours training/shadow":"Training/Mentoring",
    "metrics, burndown meeting, schedule":"Admin",
    "computer issue": "IT Issue/Update",
    "email/teams requests rpa, audit":"Email & IM",
    "emails/teams questions/collaboration":"Email & IM",
    "us sr/rd shadowing":"Training/Mentoring",
    "metrics, meetings, schedule, email":"Admin",
    "meeting with jerlie on burndown":"Meeting",
    "email/teams rpa request": "RPA Meeting/Action",
    "rpa requests/collaboration": "RPA Meeting/Action",
    "team collabration":"Collaboration",
    "pulled metrics for scrum":"Scrum & Action",
    "training, collaboration, emails/admin":"Admin",
    "ng, collaboration, ps requests, meeting":"Next Gen",
    "collaboration, meetings, lates update":"Collaboration",
    "collaboration, holiday presentation":"Collaboration",
    "holiday program activitie":"Meeting",
    "training, late mdr, metrics, cross collab qs, metrics/schedule, cornerstone":"Training/Mentoring",
    "holiday program training - no meetings but lots of troubleshooting collaboration":"Collaboration",
    "precedent event review, metrics/scrum/schedule, late tracker, meeting":"Scrum & Action",
    "schedule, metrics, collaboration":"Admin",
    "metrics, schedule, stacy qs, code gov, teammate call":"Admin",
    "emails/teams question":"Email & IM",
    "email/teams rpa & regulatory":"Email & IM",
    "reviwed affera training material for anna wright/stacy r.":"Training/Mentoring",
    "reverse shadow":"Training/Mentoring",
    "team collaboration, review event with jyn & jerlie":"Collaboration",
    "tem collaboration":"Collaboration",
    "2 meetings, rpa questions/request":"Meeting",
    "training, admin, collaboration":"Admin",
    "two 30 minute meeting":"Meeting",
    "collaboration, meeting":"Meeting",
    "rpa/reliability email/phone call": "RPA Meeting/Action",
    "pulling metrics and reviewing what was required to be done, collobartion":"Admin",
    "metrics, d2d, planning, schedule":"Admin",
    "time to enter in cap mgmt tracker":"Fill Out Capacity Management Tools (heijunka, Non-wip Chart)",
    "affera ftq work":"Project Work",
    "meetings - affera ftq & affera data file":"Meeting",
    "training, scrum, collab":"Scrum & Action",
    "metrics/schedule/scrum":"Scrum & Action",
    "schedule, metrics, scrum, ageing event investigation, email":"Scrum & Action",
    "metrics, reliability meeting, schedule, scrum":"Scrum & Action",
    "metrics/schedule/scrum, lates meeting":"Scrum & Action",
    "ng, collaboration, email/admin":"Next Gen",
    "rpa requests, email": "RPA Meeting/Action",
    "rpa emails, affera meeting/team": "RPA Meeting/Action",
    "rpa requests - email, team": "RPA Meeting/Action",
    "meeting w/ reliability":"Meeting",
    "training, meetings, ng, collab":"Training/Mentoring",
    "metrics, scrum, scheudle, ri, batchman, townhall":"Scrum & Action",
    "ri, metrics/scrum/schedule":"Scrum & Action",
    "team collaboration & email":"Collaboration",
    "goal setting/mid yr development planning / town hall":"Career Development",
    "metrics, meetings, ri":"RI",
    "metrics, gemba prep, code gov, ri":"Admin",
    "team collaboration, met stacy poe":"Collaboration",
    "ng, ms, event review, emails, colloboration, filling out pa board": "Next Gen",
    "ng, coding, emails, filling out pa board":"Email & IM",
    "training, collaboration, meetings, ms/product, filling out pa, email": "Training/Mentoring",
    "ng, coding, event reviews, emails/messages, colloboration, filling out pa board": "Event Reviews",
    "/request for affera monitoring":"Data Request",
    "on training prep": "Training/Mentoring",
    "affera question":"Question",
    "reviewed the training from liam for the new mir": "Training/Mentoring",
    "nh training": "Training/Mentoring",
    "training nhs": "Training/Mentoring",
    "email/im":"Email & IM",
    "ri temp handoff mtg":"RI",
    "career dev review":"Career Development",
    "next gen call recording": "Next Gen",
    "acrum":"Scrum & Action",
    "sh letter querie":"Question",
    "call after scrum":"Scrum & Action",
    "global town hall":"Meeting",
    "restore lsh bridge review":"LSH Bridge",
    "rs inbox":"Inbox Maintenance",
    "next gen call":"Next Gen",
    "meeting & action": "Meeting",
    "cornerston":"Cornerstone",
    "team lead meeting & action": "Meeting",
    "pmq cr pre-meeting q's review & pre-meeting call":"PMQ Meeting",        
}