name: keepalive
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # still allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        env:
          URL: ${{ secrets.KEEPALIVE_URL }}
        run: |
          echo "Pinging $URL at $(date)"
          curl -I -L --max-time 15 --retry 2 -sS "$URL"
