name: keepalive
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app root
        env:
          URL: ${{ secrets.KEEPALIVE_URL }}
        shell: bash
        run: |
          set +e
          echo "Pinging: $URL"
          RESP=$(curl -L --max-redirs 5 --max-time 20 --retry 2 --retry-delay 2 \
                    -A "Mozilla/5.0 (keepalive)" \
                    -H "Cache-Control: no-cache" \
                    -s -o /dev/null -w "%{http_code} %{url_effective}" \
                    "$URL?ping=$(date +%s)")
          echo "Result: $RESP"
          exit 0
